Src/PrtDist/Samples/PingPong/MainFunction.c
Src/PrtDist/Samples/PingPong/PingPong.vcxproj

- PingPong.exe crashes when run as "PingPong.exe" without a / or \ in the
path.
- PingPong.exe was getting copied to PingPongFast instead of PingPong
directory.

Fix a couple of issues with PingPong sample.

---

Bld/build.sh

This makes the build script executable from outside the Bld dir. It was
the only part of the build that didn't have this property and there is
no real reason not to have it.

push $SCRIPTPATH before building runtime

---

Bld/build.sh

xbuild has been deprecated and msbuild is available since Mono 5.0
- This patch makes the build script check for msbuild before falling
back to xbuild.
- It also allowes forcing the build program in the environment.

Allow using msbuild instead of xbuild

---

Src/Pc/CompilerCore/Backend/IRTransformer.cs
Tst/RegressionTests/Feature3Exprs/Correct/ShortCircuitEval/ShortCircuitEval.p

This change modifies the IR transformer to transform`&&` and `||` into code which uses `if` statements to implement short-circuiting behavior.  It turns out the test suite already contained a regression test to check the short-circuiting behavior of boolean operators, but the code to test it was intentionally commented out until the feature was implemented.  Rather than create a new regression test, I uncommented the code in this existing test.

Add short-circuiting behavior for boolean operators `&&` and `||`

---

Src/Prt/Core/PrtValues.c

The previous merge for set datatype broke some tests and was found to have clipped a return statement. This followup fixes the mistake.

set type followup fix

---

Src/CoyoteRuntime/CoyoteRuntime.csproj
Src/CoyoteRuntime/GodMachine.cs
Src/CoyoteRuntime/PMachine.cs
Src/CoyoteRuntime/PMonitor.cs
Src/Pc/CompilerCore/Backend/Coyote/CoyoteCodeGenerator.cs
Src/Samples/PingPongCoyote/Main.cs
Src/Samples/PingPongCoyote/PingPongCoyote.csproj
Src/Samples/TwoPhaseCommit/TwoPhaseCommit.csproj
Tst/UnitTests/Runners/CoyoteRunner.cs
Tst/UnitTests/UnitTests.csproj
Tutorial/Failover/FailOver.cs
Tutorial/Hello/Hello.cs

Hey @ankushdesai, this PR upgrades P to the latest Coyote (`rc6`), which includes passing events as the in-parameter to an event-handler to improve programmability (rather than using the `ReceivedEvent` property, which has now been removed).

Upgrade to coyote rc6

---

.gitignore
Src/CoyoteRuntime/CoyoteRuntime.csproj
Src/CoyoteRuntime/PLogFormatter.cs
Src/CoyoteRuntime/PMachine.cs
Src/Pc/CompilerCore/Backend/Coyote/CoyoteCodeGenerator.cs
Src/Samples/PingPongCoyote/Main.cs
Src/Samples/PingPongCoyote/PingPongCoyote.csproj
Src/Samples/TwoPhaseCommit/TwoPhaseCommit.csproj
Tst/UnitTests/Runners/CoyoteRunner.cs
Tst/UnitTests/UnitTests.csproj

**Don't merge this until the next Coyote update...** I'm just giving folks a heads up... `IActorRuntimeLogFormatter` is going away.  You can still implement your own entirely custom `IActorRuntimeLog` like we did with the `ActorRuntimeLogGraphBuilder`, or you can subclass  a new "text logging" implementation of this interface called `ActorRuntimeLogTextFormatter`.  The next coyote update also provides a new "--xml-trace" option which uses a new `IActorRuntimeLog` implementation called `ActorRuntimeLogXmlFormatter`.  This replaces the old crufty *.pstrace files with a much more machine readable xml format which might also be handy for any tooling you build around these logs.

Update PLogFormatter to new IActorRuntimeLog.

---

NuGet.config
P.sln
Src/CoyoteRuntime/CoyoteRuntime.csproj
Src/CoyoteRuntime/Exceptions/PNonStandardReturnException.cs
Src/CoyoteRuntime/PLogFormatter.cs
Src/CoyoteRuntime/PMachine.cs
Src/CoyoteRuntime/PModule.cs
Src/CoyoteRuntime/PMonitor.cs
Src/Pc/CompilerCore/Backend/Coyote/CoyoteCodeGenerator.cs
Src/Samples/PingPongCoyote/Main.cs
Src/Samples/PingPongCoyote/PingPongCoyote.csproj
Src/Samples/PingPongCoyote/Test.cs
Src/Samples/TwoPhaseCommit/TwoPhaseCommit.csproj
Tst/UnitTests/Runners/CoyoteRunner.cs
Tst/UnitTests/UnitTests.csproj
Tutorial/TwoPhaseCommit/TwoPhaseCommit.csproj
azure-pipelines.yml

There is no reason to expose Transition objects and force users to "return" a Transition.  As is evidenced by the dangling Transition PR, it didn't actually improve things and the solution to dangling Transitions shows that exposing Transition is not required to ensure the same contract (namely, that only one is created per action) as shown by the internal PendingTransition member variable.
We also decided to rename some methods to make them all have a similar and therefore consistent name:
```
RaiseEvent is unchanged
Rename “GotoState” to “RaiseGotoStateEvent”
Rename “PushState” to “RaisePushStateEvent”
Rename “PopState” to “RaisePopStateEvent”
Rename “Halt” to “RaiseHaltEvent”
```
The idea being that the "Raise...Event" language more clearly communicates to the user that these …

Coyote is hiding the Transition type. 

---

Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeGenerator.cs
Tst/RegressionTests/Feature4DataTypes/Correct/enum4/enum4.p
Tst/RegressionTests/Feature4DataTypes/DynamicError/enum1/enum1.p
Tst/RegressionTests/Feature4DataTypes/StaticError/enum1/enum1.p

Fixed a bug in the CSharp generated code with respect to default value of Enums. Closes #275

Fixed the bug associated with default value of Enum.

---

Src/PCompiler/CommandLine/CommandLineOptions.cs

`option` does not require to preliminary be lower cased.
Case sensitivy is further detected by the IsCorrectPProjFileName.
Without this patch any call on unix cs fs does not work:
$ ./Bld/Drops/Release/Binaries/netcoreapp3.1/P -proj:./Tutorial/TwoPhaseCommit/TwoPhaseCommit.pproj

fix pproj path extraction on unix case sensitive file systems

---

Src/PCompiler/CommandLine/CommandLineOptions.cs
Src/PCompiler/CommandLine/ParseCommandlineOptions.cs
Src/PCompiler/CompilerCore/Backend/Rvm/AjFileGenerator.cs
Src/PCompiler/CompilerCore/Backend/Rvm/RvmNameManager.cs
Src/PCompiler/CompilerCore/CompilationJob.cs
Src/PCompiler/CompilerCore/DefaultCompilerOutput.cs
Src/PCompiler/CompilerCore/ICompilationJob.cs

1. Instead of generating AspectJ template file, it outputs BaseAspect that a user does not need to modify
2. P compiler takes "-aspectOutputDir" argument to output all aspectj files into this directory
3. BaseAspect file implements the `@MonitorOn` annotation and short aliases of event handler calls

Change input AspectJ code, Add aspectj output dir option, Generate BaseAspect

---

Src/PCompiler/CompilerCore/DefaultTranslationErrorHandler.cs
Src/PCompiler/CompilerCore/TypeChecker/StatementVisitor.cs

Currently, if a `goto` is used with an incorrect number of arguments, the typechecker reports a type mismatch.  For instance, consider the following program:
```
1 machine Node
2 {
3   start state Init {
4   entry
5     {
6       goto NewState; // Missing an argument!
7     }
8   }
9
10   state NewState {
11     entry (arg: int) {
12       print format ("Transitioned to NewState with {0}", arg);
13     }
14   }
15 }
```
Presently the error on line 6 is: `got type: (), expected: Node`. This is confusing for two reasons: the user didn't explicitly construct the empty tuple (it's a second-order effect of not passing arguments to the state transition), and because `NewState::entry` expects a single argument (which gets collapsed to a scalar value in `VisitGotoStmt()`), there's no indication …

More specific error on a `goto` argument arity mismatch

---

Tutorial/1_ClientServer/PSpec/BankBalanceCorrect.p

Currently, on processing a WithDrawResp, if the new balance from the bank
doesn't match what the spec expects, we print out our balance, not the balance
with the withdraw applied to it.  Concretely, consider the following
events:
```
eInit( { 100: 42, 101: 10 } )
eWithDrawReq(Client: 1, accountId: 100, amount: 10, rId: 0)
eWithDrawResp(status: WITHDRAW_SUCCESS, accountId: 100, balance: 1000, rId: 0)
```
Note that the "balance" field is described as "`balance`: bank balance after withdrawal".
Clearly this should violate the spec: withdrawing 10 from a balance of 42
should yield a new balance of 32, not 1000!  However, the assert message
states,
```
Transitioning to Init
DEBUG: In prt.State[Init]: processing event pEvent eSpec_BankBalanceIsAlwaysCorrect_Init[payload={100=42, 101=10}] …
```

[Tutorial] minor fix in BankBalanceCorrect.p assert message

---

Src/PRuntimes/PSymbolicRuntime/build.gradle
Src/PRuntimes/PSymbolicRuntime/pom.xml

Swap out Log4J 1.x dependency with the Log4j1-2 adaptor instead and upgrade guava to 30.0.
Tested with the `./build.sh` script in `Src/PRuntimes/PSymbolicRuntime/scripts`.

[PSymbolicRuntime] Bump dependency versions

---

Src/PCompiler/CompilerCore/TypeChecker/Scope.cs
Src/PCompiler/CompilerCore/TypeChecker/TypeResolver.cs
Src/PCompiler/CompilerCore/TypeChecker/Types/TupleType.cs

This is part of the non-Java compiler work required to implement https://github.com/dijkstracula/prtsandbox/issues/12 .
Ankush, you might not like my choice of implementing `TupleType::ToNamedTupleType()`.  Let me know and we can iterate on that.

[TypeChecker] Accumulate all tuple types into Scope

---

Src/PCompiler/CompilerCore/Backend/Java/JavaCodeGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs
Src/PCompiler/CompilerCore/TypeChecker/AST/Expressions/BinOpType.cs

Previously, a generated class `.deepEquals()` would simply call into `Values.deepEquals()`, which would in turn, in the runtime, call `Objects.deepEquals()`.  However, I misunderstood the semantics of Objects.deepEquals() so that wasn't the right thing, so a [patch](https://github.com/dijkstracula/prtsandbox/pull/26) went out to the Java runtime which manually switches on all the PRT types we expect.
For generated classes, though, we need to iterate through all the fields of the class and checking equality on each of them, so there is a compiler component here too.
Here's an example (notice that deepEquals calls are elided for primitive types):
```java
// (key:string,val:int,transId:int)
public static class PTuple_key_val_transId implements Values.PTuple<PTuple_key_val_transId> {
public …
```

[Java] Emit per-field deep equality check

---

Src/PRuntimes/PCSharpRuntime/PLogFormatter.cs
Src/PRuntimes/PCSharpRuntime/Values/IPrtValue.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtMap.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtSeq.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtSet.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtString.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtTuple.cs

This is an attempt to address https://github.com/p-org/P/issues/447 , but we
should think carefully about whether we've covered our bases on this.
Previously, the PLogFormatter would emit the direct string representation
of any PrtValues in an event payload.  This means that there could be ambiguity
owing to PrtStrings not being escaped.  For instance, the P statement
```
send f, ev, (s = "a:string, with:\"problems",);
```
Would yield a log line of the form:
```
<SendLog> 'PImplementation.Driver(2)' in state 'Init_1' sent event 'ev with payload (<s:a:string, with:"problems, >)' to 'Foo(3)'
```
Which is ambiguous in terms of what the NamedTuple arity is, and also
results in an unclosed string literal.
This patch introduces a variation on ToString(), called ToEscapedString(),
which ensures …

[PCSharpRuntime] Log an escaped string representation of PrtValues

---

Src/PRuntimes/PCSharpRuntime/PLogFormatter.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtMap.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtSeq.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtSet.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtString.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtTuple.cs
Tst/RegressionTests/Combined/Correct/nullPayload/nullPayload.p

After ee5f456a9bb30141d2ca24cadff977084bc1fffc , logging output used escaped PrtValue string representations using a `toEscapedString()` method rather than coercing the PRT object to its string representation.  The latter is null-safe:
```
SomeObject o = null;
string s = $"The object is \"{o}\"!";
Console.WriteLine(s);
```
produces `The object is ""!`.  The former, however, is not.  This is problematic for null event payloads.  Consider:
```
1  event ev : any;
2
3  machine Foo {
4    start state Init {
5      on ev do (x: any) { }
6    }
7  }
8
9  machine Driver {
10    var f: Foo;
11
12    start state Init {
13      entry {
14        f = new Foo();
15        send f, ev, (s = null,);
16      }
17    }
18  }
19
20  test doIt [main=Driver]: (union {Driver}, {Foo});
```
Which results in a …

Fix NPE in ToEscapedString() with null payloads

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/EventGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/JavaCompiler.cs
Src/PCompiler/CompilerCore/Backend/Java/JavaSourceGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineCodeGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs

Previously all Java code was emitted into a single Java file, named after the P project.  This was just like the C# code generator.
This patch now generates Events in their own file, called `Events.java` (but still in the same package).  As a forward reference for future changes, that blob of Java code is now called `Machines.java` - as there are now multiple code generators working in tandem, and since identifiers need to be referenced between files, it proved to be exceedingly awkward to thread through the top level name for this file.
```
nathta@bcd0741cf59d pprojtest % cat -n PSpec/foo.p
1  type t = (a: int, b: seq[int]);
2
3  event eIncr : t;
4  event eOther;
5  event eYetAnother;
6
7  spec monitorA observes eIncr {
8    start state Init {
9      entry {}
10      on eIncr do {}
11 …
```

[Java] generate Java source for events in their own file

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/JavaSourceGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs
Src/PCompiler/CompilerCore/Backend/Java/TypesGenerator.cs

Initially, for simplicity, P enums were just extracted to Java as
plain old static ints, and we lost all P enum-specific type information
in Java.  Consider the very silly P program:
```
nathta@bcd0741cf59d pprojtest_enum % cat -n PSpec/foo.p
1  enum anEnum {
2    VALUE_ZERO,
3    VALUE_ONE
4  }
5
6  event eIncr : anEnum;
7
8
9  spec monitorA observes eIncr {
10    var myE : anEnum;
11    start state Init {
12      entry {
13        myE = VALUE_ZERO;
14      }
15      on eIncr do (e: anEnum) {
16        assert e == VALUE_ONE, "uh oh";
17      }
18    }
19  }
nathta@bcd0741cf59d pprojtest_enum %
```
As of tag 1.13:
```java
12     /* Enums */
13     public static class anEnum {
14         public static final int VALUE_ZERO = 0;
15         public static final int VALUE_ONE = 1;
16     }
... …
```

[Java] Emit proper Java enums for P enums

---

Src/PCompiler/CompilerCore/Backend/Java/JavaSourceGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypesGenerator.cs

This is needed to fulfill the interface on the PObserve side.
Sample output:
```
40         public java.util.List<Class<? extends prt.events.PEvent>> getEventTypes() {
41             return java.util.Arrays.asList(PEvents.eSpec_BankBalanceIsAlwaysCorrect_Init.class, PEvents.eWithDrawReq.class, PEvents.eWithDrawResp.class);
42         }
```
And also a small refactoring patch to hide a bit of gnarly iteration logic.

[Java] emit code for .getEventType()

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/FFIStubGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/JavaCompiler.cs
Src/PCompiler/CompilerCore/Backend/Java/JavaSourceGenerator.cs
Src/PRuntimes/PJavaRuntime/src/main/java/prt/exceptions/IncomparableValuesException.java
Src/PRuntimes/PJavaRuntime/src/main/java/prt/values/Equality.java
Src/PRuntimes/PJavaRuntime/src/test/java/ValueCompareTest.java

This is a partial solution to an issue I noticed this morning:
I noticed a problem with the pproj FFI example: it compiles cleanly, but would behave incorrectly should it execute: [The FFI type](https://github.com/dijkstracula/pprojexample/blob/main/PForeign/globals/Counter.java) needs to implement `deepEquals` and `deepClone`, but doesn't (it should have implemented an interface), so we would find ourselves in a situation where we emit compiling Java code that calls into runtime type checking code on the PRT side, and would do the wrong thing - essentially, the "do these values inherit from PValue" checks would fail, so identical Counters [would fall through and test as being unequal](https://github.com/p-org/P/blob/2f060bf22f1f1d449c23a99ebfa4cffc298e2267/Src/PRuntimes/PJavaRuntime/src/m …

[Java] Emit FFI stub implementations

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs

This patch makes any P projects that compile to Java include the Java P runtime within the JAR.
Additionally: we do not include transitive dependencies like log4j in here, since if whoever is loading this jar also uses it then there would be a namespace collision.
```
nathta@bcd0741cf59d 1_ClientServer % pcl -proj:ClientServer.pproj
----------------------------------------
==== Loading project file: ClientServer.pproj
....... includes p file: /Users/nathta/code/P/Tutorial/1_ClientServer/PSrc/Server.p
....... includes p file: /Users/nathta/code/P/Tutorial/1_ClientServer/PSrc/Client.p
....... includes p file: /Users/nathta/code/P/Tutorial/1_ClientServer/PSrc/AbstractBankServer.p
....... includes p file: /Users/nathta/code/P/Tutorial/1_ClientServer/PSrc/ClientServerModules.p
....... includes …
```

[Java] Generate extracted JARs with PRT

---

Src/PCompiler/CompilerCore/Backend/Java/FFIStubGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/JavaSourceGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs

This patch puts out all arguments to foreign function stubs on their own line;
previously, all arguments were on one line and it they proved to be difficult
to read; this now matches hand-written C# FFI bindings observed elsewhere.
Additionally, a divider line was emitted for every P Machine, even if there
were no foreign functions for that machine.  As a result, the stub file would
have multiple lines delimiting no lines of Java stubs.  This patch only emits
the dividing line if there is anything to emit for a given machine.

[Java] better FFI stub formatting

---

Src/PRuntimes/PJavaRuntime/src/main/java/prt/Monitor.java
Src/PRuntimes/PJavaRuntime/src/test/java/MonitorTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/tutorialmonitors/clientserver/ClientServerTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/tutorialmonitors/espressomachine/EspressoMachineTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/tutorialmonitors/failuredetector/FailureDetectorTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/tutorialmonitors/twophasecommit/TwoPhaseCommitTest.java

Having this interface inherit directly from a built-in Java type
simplifies code-sharing across different projects.

[Java] prt.Monitor to implement Consumer<PEvent>

---

Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PRuntimes/PJavaRuntime/pom.xml

This was a PRT refactoring change that somehow didn't get changed on the runtime side, and somehow I missed with testing.  Mea culpa.
```
nathta@bcd0741cf59d /tmp % pcl -generate:Java foo.p
----------------------------------------
....... includes p file: /private/tmp/foo.p
----------------------------------------
----------------------------------------
Parsing ...
Type checking ...
Code generation ...
Reusing existing pom.xml
Generated PMachines.java.
Generated PEvents.java.
Generated PTypes.java.
Generated FFIStubs.txt.
----------------------------------------
Compiling foo...
----------------------------------------
nathta@bcd0741cf59d /tmp % grep 'throws prt\.' PMachines.java
private void Anon_1() throws prt.exceptions.TransitionException {
nathta@bcd0741cf59d /tmp %
```
This patch …

[Java] generate exceptions from prt.exceptions package

---

Src/PCompiler/CompilerCore/Backend/Java/TypesGenerator.cs

The following spec should compile:
```
1 type t = (a: int, b: int);
2 event e: int;
3
4 spec m observes e {
5   var v: t;
6   start state Init {
7     on e do {
8       v.a = 42;
9       v.b = 99;
10     }
11   }
12 }
```
However, as part of the assertion that all P values are values, the generated fields in the class definition for `t` were marked as final, so this code wouldn't compile at the Java end:
```
[ERROR] /private/tmp/PMachines.java:[32,14] cannot assign a value to final variable a
[ERROR] /private/tmp/PMachines.java:[33,14] cannot assign a value to final variable b
```
This patch simply removes the `final` designation of those fields.

[Java] do not generate tuple fields as final

---

Src/PCompiler/CompilerCore/Backend/Java/JavaCompiler.cs
Src/PCompiler/CompilerCore/Backend/Java/JavaSourceGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs

Previously the code generator for the events, types, and machines Java files would not share a compilation context.  This means that NameManagers (and therefore TypeManagers) would not be shared between files.  This is problematic for the case where we have to disambiguate identifier names; the following code would fail to compile,
```
nathta@bcd0741cf59d /tmp % cat -n foo.p
1  type t1 = (a: int, b: float);
2  type t2 = (a: int, b: string);
3
4  event e: t2;
5
6  spec m observes e {
7    var s: string;
8    start state Init {
9      on e do (ev: t2) {
10        s = ev.b;
11      }
12    }
13  }
14
15  machine Driver {
16    start state Init {}
17  }
18
19  test doIt [main=Driver]: {Driver};
nathta@bcd0741cf59d /tmp %
```
because a different unique name for `t2` would be generated in the …

[Java] share compilation contexts across different Java code generators

---

Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs
Src/PRuntimes/PJavaRuntime/src/main/java/prt/values/Clone.java
Src/PRuntimes/PJavaRuntime/src/test/java/ValueCloneTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/testmonitors/clientserver/ClientServerTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/testmonitors/clientserver/PEvents.java
Src/PRuntimes/PJavaRuntime/src/test/java/testmonitors/clientserver/PMachines.java
Src/PRuntimes/PJavaRuntime/src/test/java/testmonitors/clientserver/PTypes.java

Other backends use the widest integral types available on the system.

[Java] P ints should be extracted as Java Longs

---

Src/PCompiler/CompilerCore/Backend/Java/TypesGenerator.cs
Src/PRuntimes/PJavaRuntime/src/test/java/ValueCompareTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/testmonitors/clientserver/PTypes.java

Baby's first Java gotcha and I fell into it, argh!
```
nathta@bcd0741cf59d 1_ClientServer % jshell -c POutput/ClientServer-1.0-SNAPSHOT-jar-with-dependencies.jar
|  Welcome to JShell -- Version 11.0.14
|  For an introduction type: /help intro
jshell> import PGenerated.PTypes.*;
jshell> PTuple_src_accnt_amnt_rId t1 = new PTuple_src_accnt_amnt_rId();
t1 ==> PTuple_src_accnt_amnt_rId[source=0, accountId=0, amount=0, rId=0]
jshell> PTuple_src_accnt_amnt_rId t2 = new PTuple_src_accnt_amnt_rId();
t2 ==> PTuple_src_accnt_amnt_rId[source=0, accountId=0, amount=0, rId=0]
jshell> t1.equals(t2)
$4 ==> true
jshell> t1.hashCode() == t2.hashCode()
$5 ==> true
jshell>
```

[Java] generate a hashcode() implentation for named tuples

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/FFIStubGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs

This patch includes some minor fixes to the FFI stub generator that @beyazit-yalcinkaya found.  
The big one is that we couldn't generate code for foreign functions at the top P scope, as there was no associated Monitor proxy class (since there's no monitor!).  There are also a bunch of tiny fixes around FFI stub quality-of-life stuff like automatically importing the right foreign types.
An example of a P project and the new FFI-generated stubs can be see [here](https://github.com/dijkstracula/pprojexample/tree/nathan/fixes_example) for those inclined.
One attribute to this patch that might warrant some conversation is that now foreign types have a stub for `hashCode()`, and `equals()` which just defers to `deepEquals()`.  I did this because I forgot about hashCode the other day and …

[Java] minor fixes to the FFI stub generator

---

Src/PCompiler/CompilerCore/Backend/Java/JavaSourceGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs
Src/PRuntimes/PJavaRuntime/src/main/java/prt/values/Clone.java
Src/PRuntimes/PJavaRuntime/src/test/java/ClientServerTraceParser/ClientServerTraceParser.java
Src/PRuntimes/PJavaRuntime/src/test/java/ClientServerTraceParser/ClientServerTraceParserTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/ValueCloneTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/ValueCompareTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/UnboundedNat.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/clientserver/ClientServerTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/clientserver/PEvents.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/clientserver/PMachines.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/clientserver/PTypes.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/espressomachine/EspressoMachine.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/espressomachine/EspressoMachineTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/failuredetector/FailureDetector.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/failuredetector/FailureDetectorTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/twophasecommit/TwoPhaseCommit.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/twophasecommit/TwoPhaseCommitTest.java

Per [this TODO comment block](https://github.com/p-org/P/blob/1b69964fb0d64ca7acaf6f8d5be190703cb86940/Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs#L867-L875): Collections in P are covariant.  This means that because `int` is a subclass of `any`, `seq[int]` is a subclass of `seq[any]`.  We were not emitting correct Java code for cases where a downcast is expected during an assignment statement.  This patch fixes it along with some minor adjustments to extracted Java casting behaviour.
(If you are familiar with the problem with covariant collections you can skip this part)
In languages with mutable references, covariant collections are problematic:
```
jshell> String ss[] = new String[] { "Java", "Arrays", "Are", "Covariant" }
ss ==> String[4] { "Java", "Arrays", "Are", …
```

Correctly emit downcasts for covariant datatypes

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/FFIStubGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/JavaSourceGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs
Src/PRuntimes/PJavaRuntime/src/main/java/prt/Monitor.java
Src/PRuntimes/PJavaRuntime/src/main/java/prt/values/Equality.java
Src/PRuntimes/PJavaRuntime/src/main/java/prt/values/PValue.java

Noticed that this was a missing part of the FFI for Java.
For functions defined within the scope of a Machine, the FFI generator now emits a call typed to [that exact Monitor type](https://github.com/dijkstracula/pprojexample/blob/nathan/fixes_example/PForeign/Monitor.java#L9).  
For top-level function definitions, we don't know for sure which Monitor is calling the function, [so we unfortunately can't be quite as precise at the type level](https://github.com/dijkstracula/pprojexample/blob/nathan/fixes_example/PForeign/P_TopScope.java#L9), so we just emit the base Monitor type instead.
This patch also makes certain state transition and assert methods that were previously protected within the Monitor type public, [so they can be called on the …

Java FFI: Functions to consume the current Machine

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/FFIStubGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/NameManager.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs

The Java backend (as with all other backends) reserves certain keywords for internal use.  Examples would be `prt` (the top-level package for the P java runtime) and `PEvents` (the package where all P events are stored).  This means that P programs can't use those keywords as P-language identifiers in a safe manner.  Consider the following slightly silly program:
```
nathta@bcd0741cf59d /tmp % cat -n foo.p
1  enum PValue {
2    VALUE_ZERO,
3    VALUE_ONE
4  }
5
6  event PEvent : PValue;
7
8  spec PMachines observes PEvent {
9    var PEvents: set[PValue];
10    start state P_TopScope {
11      entry {
12      }
13    }
14  }
nathta@bcd0741cf59d /tmp %
```
This of course is an extreme example but there's no reason why a P programmer should believe this shouldn't compile.  (For instance, …

[Java] rename tokens reserved by the Java backend

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PRuntimes/PJavaRuntime/src/main/java/prt/values/SetIndexing.java
Src/PRuntimes/PJavaRuntime/src/test/java/ValueSetElementAtTest.java

In P, iteration through a `set[T]` is done by an integral index iterating from 0 to the size of the set.  In both the [C#](https://github.com/p-org/P/blob/1c3fb7e8190c0f50cb38afe3905e72f56a950ee9/Src/PRuntimes/PCSharpRuntime/Values/PrtSet.cs#L139-L143) and [Java](https://github.com/p-org/P/blob/a1e547d4319de862f6d110b302497f06f8feddd2/Src/PRuntimes/PJavaRuntime/src/main/java/prt/values/SetIndexing.java#L8-L21) backends, to access the `i`th element requires `i` iterations through a linked list; as a result, iterating through every element in a set is [accidentally quadratic](https://accidentallyquadratic.tumblr.com/).
Here's a benchmark of a P event handler that simply iterates through a `set[int]` of `n` elements in sequential order; essentially, 
```
3 spec m observes e {
4   var numbers …
```

[Java] Linear time sequential iteration for P sets

---

Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PRuntimes/PJavaRuntime/src/test/java/ValueSetElementAtTest.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/clientserver/PMachines.java

Currently, all local variables in an extracted function are properly declared and defined with a valid initial value.  Here's a snippet from the local variable definition of a non-trivial function:
```java
...
PTypes.a_b_c TMP_tmp7_1 = new PTypes.a_b_c();
LinkedHashSet<PTypes.PTuple_foo_bar_baz_quz> TMP_tmp8 = new LinkedHashSet<PTypes.PTuple_foo_bar_baz_quz>();
PTypes.PTuple_foo_bar_baz_quz TMP_tmp9 = new PTypes.PTuple_foo_bar_baz_quz();
String TMP_tmp10 = "";
long TMP_tmp11 = 0L;
PTypes.a_b_c TMP_tmp12 = new PTypes.a_b_c();
PTypes.a_b_c TMP_tmp13 = new PTypes.a_b_c();
PTypes.PTuple_foo_bar_baz_quz TMP_tmp14 = new PTypes.PTuple_foo_bar_baz_quz();
String TMP_tmp15 = "";
String TMP_tmp16 = "";
...
```
These are all prefaced with `TMP_`, indicating that they're emitted only as part of the …

[Java] do not initialise temporary variables

---

Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/NameManager.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/clientserver/PEvents.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/clientserver/PMachines.java
Src/PRuntimes/PJavaRuntime/src/test/java/testcases/clientserver/PTypes.java

Previously we were only importing foreign type names when generating
Monitors, but not Events - this inconsistency lead to compilation
errors in complicated specs.  This patch makes us consistent in
that we always have to fully qualify the type, obviating the need for
the import.

[Java] fully qualify foreign types

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/TypeChecker/Types/TupleType.cs

Unnamed tuple code generation has a few issues, which I noticed while splunking in some old code during benchmarking.  Here's a sample program:
```
nathta@bcd0741cf59d /tmp % cat -n foo.p
1  type t = (int, int, seq[int]);
2  event e: t;
3
4  spec M observes e {
5    start state S {
6      on e do (a: t) {
7        a.0 = a.1;
8      }
9    }
10  }
nathta@bcd0741cf59d /tmp %
```
For context: unnamed tuples are treated by the Java type generator as if they were NamedTuples with field names "arg_0", "arg_1", and so on.
```
13     public static class PTuple_arg_0_arg_1_arg_2 implements prt.values.PValue<PTuple_arg_0_arg_1_arg_2> {
14         // (arg_0:int,arg_1:int,arg_2:seq[int])
15         public long arg_0;
16         public long arg_1;
17         public ArrayList<Long> arg_2;
...
``` …

[Java] emit correct accessors for unnamed tuples

---

Bld/build.sh
Tst/PUnit/README.md
Tst/PUnit/pom.xml

The previous patch configured the build script to also build PUnit.  However, I realised this morning that this implicitly required that the PRT is installed in the user's local Maven repository; from a clean ~/.m2 directory, I get:
```
$ ./build.sh
...
[ERROR] Failed to execute goal on project punit: Could not resolve dependencies for project org.example:prts
andbox:jar:1.0-SNAPSHOT: Could not find artifact p.runtime:PJavaRuntime:jar:1.0-SNAPSHOT -> [Help 1]
```
One simple change would be to, at build time, install that dependency - we're building it anyway, so we just need to do a `mvn install` rather than `mvn compile`.  However, I worry about implicitly installing dependencies in a build script: in particular, if a user is actively working on the PRT and also re-building P, I'm not …

[PUnit] do not build as part of build.sh

---

Src/PRuntimes/PCSharpRuntime/Exceptions/UnknownNamedTupleFieldAccess.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtTuple.cs

Tuples and named tuples in C# extract to, morally, association lists, meaning that field accesses require iterating through an array.  Currently, on an invalid field access, the exception that is thrown is not useful to users.
Imagine I am writing the foreign code for the 2PC tutorial and I mis-type one of the fields: 
```diff
diff --git a/Tutorial/2_TwoPhaseCommit/PForeign/ForeignCode.cs b/Tutorial/2_TwoPhaseCommit/PForeign/ForeignCode.cs
index c8b9af5a1..0bd3ad5c8 100644
--- a/Tutorial/2_TwoPhaseCommit/PForeign/ForeignCode.cs
+++ b/Tutorial/2_TwoPhaseCommit/PForeign/ForeignCode.cs
@@ -16,7 +16,7 @@ namespace PImplementation
{
public static PrtNamedTuple ChooseRandomTransaction(PrtInt uniqueId, PMachine pMachine)
{
-      return (new PrtNamedTuple(new string[] { "key", "val", "transId" …
```

[CSharpRuntime] bounds check on named tuple access

---

Src/PCompiler/CompilerCore/Backend/Java/FFIStubGenerator.cs

Removed the monitorType machine line the writes machine as the first parameter in FFIStubGenerator.cs.

Update FFI file to remove machien as first param

---

Src/PRuntimes/PCSharpRuntime/PMachine.cs
Tst/RegressionTests/Integration/DynamicError/SEM_TwoMachines_15/MonitorInvocationEventExprPayload.p

Fixed #510 
Also, a better error message is reported when trying to send a message and target machine is `null`

Fixed a broken regression and a better error message

---

Src/PChecker/CheckerCore/CheckerConfiguration.cs
Src/PCompiler/PCommandLine/Options/PCheckerOptions.cs
Src/PCompiler/PCommandLine/Options/PCompilerOptions.cs
Src/PCompiler/PCommandLine/Parser/ParsePProjectFile.cs

- Updates CLI options to remove `--target` and `--generate` options. Instead, `--target` is renamed to `--projname` and `--mode` is used to configure the compiler/checker backend (default: `bugfinding`). Currently available modes include: `bugfinding`, `pobserve`.
- Adds support for searching for `*.dll` in the current directory with `p check` command when path is not given
- Adds fallback support for searching for and adding local P files in the current directory with `p compile` command when no P file is given through `*.pproj` and `--pfiles` options.
- Improves error messages in commandline configuration

[CLI] Updates commandline options

---

Docs/docs/getstarted/install.md

Updates java installation instructions for AL2 to use `java-11-amazon-corretto` instead of `java-11-amazon-corretto-devel`.
`java-11-amazon-corretto-devel` seems to be no longer available on AL2.

[Docs] Minor: Update java installation for AL2

---

Tutorial/2_TwoPhaseCommit/PTst/TestDriver.p

I was following along in the 2PC tutorial and noticed this. Very minor but figured I'd send it along.

Fix typo in 2PC TestDriver.p

---

Src/PCompiler/PCommandLine/Options/PCheckerOptions.cs

Everything seems to work fine on Windows except for actually running the spec once compiled. I noticed the checker options were hard coded with `/` so I swapped it to use the character from `Path`.
I can run specs on Windows now!
Would you be open to another PR that adds a "Developing P" section to the readme? I had to look up how to install local versions of `dotnet` tools which took longer than coding up this fix. You might also assume that this is relatively common knowledge and not want to duplicate it in your repository though.

PCheckerOptions fix file path search

---

.github/workflows/tutorials.yml
Src/Scripts/TutorialsChecker/check.sh
Src/Scripts/TutorialsChecker/compile.sh

GitHub action for Tutorials was picking up the latest P version on NuGet and using it to run the GitHub action.
What we instead need in our CI is that P is built from the current code commit (like all other GitHub actions).
This PR adds support for this.
Also, the shell script [check.sh](https://github.com/p-org/P/blob/master/Src/Scripts/TutorialsChecker/check.sh#L30) was incorrectly parsing the test cases (due to the recent P change "[PTool]" became "~~ [PTool]"). Corrected.

[CI] Fix Tutorial GitHub Action

---

Tutorial/3_EspressoMachine/PTst/TestScripts.p

Sorry for bothering you with such a trivial fix, but it should match the checking command in the tutorial.

Fix the name of the coffee machine testcase

---

Src/PChecker/CheckerCore/Actors/Logging/JsonWriter.cs
Src/PChecker/CheckerCore/SystematicTesting/TestingEngine.cs

\+ JSON verbose logs output file when running verbose mode
> Structure is a list of list of logs. i.e. `[iter 1 logs, iter 2 logs, iter 3 logs, ...]`
\+ modified emit trace for JSON formatter to stream to file while serializing at the same time

json verbose logs output

---

Src/PCompiler/CompilerCore/Backend/Symbolic/SymbolicCodeGenerator.cs
Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/PSymConfiguration.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/PSymOptions.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/machine/events/Message.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/replay/ReplayScheduler.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/explicit/ExplicitSearchScheduler.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/explicit/ExplicitSymmetryTracker.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/explicit/StateCachingMode.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/symbolic/SymbolicSearchScheduler.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/MapVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/NamedTupleVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/PrimitiveVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/TupleVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/UnionVS.java
Src/PRuntimes/PSymRuntime/src/test/java/psym/TestSymbolicRegression.java

[PSym]
- Corrects symbolic comparison with nested null values in tuples casted as any
- Codegen: correct default null value guards
- Correct Map value summary get operation with any or null values
- Correct tuple value summary merging with null or any sub fields
- New improved symbolic state caching mode with support for incremental pruning and fixpoint detection (WIP)
[PCover]
- Support dependent fields during symmetry detection (WIP)
- Make Map type hashing to be key-order independent

[PSym/PCover] Updates

---

Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeGenerator.cs

Force non-incremental flag when building C# generated code to avoid stale version mismatch from different versions of P. 
Before the fix, running `p compile` followed by `pl compile` should throw a compile error (like https://github.com/p-org/peasy-ide-vscode/issues/23) if local P version (i.e., `pl`) does not match official (i.e., `p`). Similar issue can happen when updating P and using latest P release version on project previously built with an old release.
After the fix, the error should go away, since `--no-incremental` forces the C# generated code to perform `clean and build` instead of just `build`, thus ignoring previous dotnet object files that can trigger such error due to P .dll version mismatch.

[PCompiler] Fix stale version mismatch

---

Src/PChecker/CheckerCore/Actors/Logging/JsonWriter.cs
Src/PRuntimes/PCSharpRuntime/PJsonFormatter.cs

\+ Previous vector clock generation didn't handle ReceiveEvent properly, fixed now
\+ Fixed some machine naming inconsistencies

fixed vector clock for ReceiveEvent, fixed naming consistency

---

.github/workflows/psymit.yml
Src/PRuntimes/PSymRuntime/pom.xml
Src/PRuntimes/PSymRuntime/src/main/java/psym/EntryPoint.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/PSymConfiguration.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/PSymOptions.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/machine/events/Message.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/Schedule.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/Scheduler.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/replay/ReplayScheduler.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/SearchScheduler.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/explicit/ExplicitSymmetryTracker.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/symbolic/SymbolicSearchScheduler.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/symbolic/SymbolicSymmetryTracker.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/symmetry/SymmetryTracker.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/ListVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/MapVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/NamedTupleVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/PrimitiveVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/SetVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/TupleVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/UnionVS.java
Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/ValueSummary.java
Src/PRuntimes/PSymRuntime/src/test/java/psym/TestCaseExecutor.java
Src/PRuntimes/PSymRuntime/src/test/java/psym/TestSymbolicRegression.java

[PSym]
- Adds symbolic state caching with support for pruning explored states and fix point detection
- Updates CLI to include new symbolic strategies: symbolic-fixpoint and symbolic-iterative (choices bounded to 2 per iteration)
- Cex replayer: corrects behavior with dynamic machine creation in PSym mode
[PCover]
- Adds core algorithm to track dependent fields and perform symmetry-aware search with them
[CI]
- Minor updates relating to configuring checker run for PSym

[PSym/PCover] Add fixpoint, symmetry search

---

Src/PChecker/CheckerCore/Actors/Logging/JsonWriter.cs
Src/PRuntimes/PCSharpRuntime/PEvent.cs
Src/PRuntimes/PCSharpRuntime/PJsonFormatter.cs
Src/PRuntimes/PCSharpRuntime/PMachine.cs
Src/PRuntimes/PCSharpRuntime/Values/IPrtValue.cs
Src/PRuntimes/PCSharpRuntime/Values/PMachineValue.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtBool.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtEnum.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtFloat.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtInt.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtMap.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtSeq.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtSet.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtString.cs
Src/PRuntimes/PCSharpRuntime/Values/PrtTuple.cs

\+ Added JSON representation of payload all P data types, beyond just named tuples
Added `object ToDict()` method for all `IPrtValues`
JSON payload should you represent all valid P data types, including nested data types.
```
{
[index]: value,
...
}
Example: (0, false, "foo") becomes
{
0: 0,
1: false,
2: "foo",
}
```
```
{
[name]: value,
...
}
Example: (client=Client(7), trans=(key=8, val=8, transId=12)) becomes
{
"client": "Client(7)",
"trans": {
"key": 8,
"val": 8,
"transId": 12
}
}
```
```
[value itself]
Example: int 8 becomes
8
bool false becomes
false
etc...
```
```
{
[name]: [int value],
...
}
Example: { ERROR = 500, SUCCESS = 200, TIMEOUT = 400; } becomes
{
"ERROR": 500,
"SUCCESS": 200,
"TIMEOUT": 400,
}
```
```
{
[key]: [value],
...
}
Example: (<key1 -> 2>, <key2 -> 4>) becomes
{ …
```

Added JSON representation of payload of all types, beyond named tuples

---

Src/PChecker/CheckerCore/Actors/Actor.cs
Src/PChecker/CheckerCore/Actors/ActorRuntime.cs
Src/PChecker/CheckerCore/Actors/Logging/JsonWriter.cs
Src/PChecker/CheckerCore/Actors/Logging/LogWriter.cs
Src/PChecker/CheckerCore/Specifications/Monitors/Monitor.cs
Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeGenerator.cs
Src/PRuntimes/PCSharpRuntime/PMachine.cs
Src/PRuntimes/PCSharpRuntime/PMonitor.cs

```
{
"type": "Print",
"details": {
"log": "Withdrawal with rId = 3 failed, account balance = 13"
}
},
```
```
{
"type": "Announce",
"details": {
"log": "TestWithSingleClient(2) announced event eSpec_BankBalanceIsAlwaysCorrect_Init with payload (\u003C0-\u003E107\u003E).",
"id": "TestWithSingleClient(2)",
"event": "eSpec_BankBalanceIsAlwaysCorrect_Init",
"payload": {
"0": 107
},
"clock": {
"TestWithSingleClient(2)": 2
}
}
},
```

JSON logs Announce and Print actions

---

Src/PChecker/CheckerCore/Actors/Logging/JsonWriter.cs
Src/PRuntimes/PCSharpRuntime/PJsonFormatter.cs

For `OnMonitorProcessEvents`, the monitor's vector clock will be connected to the `senderMachine`'s vector clock so there is some timeline association between when the monitor processed the event and when the senderMachine sent the event. 
The issue before was that since there was no association between the monitor's and the senderMachine's events, all the monitor's individual events get's stacked.
Now, the individual events are expanded to better align with when the event was actually sent.

Vector clock updated for OnMonitorProcessEvents

---

Src/PChecker/CheckerCore/CheckerConfiguration.cs
Src/PCompiler/CompilerCore/Backend/Stately/StatelyCodeGenerator.cs

This PR fixes the below issues:
1. The P output files were moved before replay command is run, causing a "File not found" error
2. The stately generator code was generating duplicate handlers for a state

Fix p check replay bug and stately code generator bug

---

Src/PChecker/CheckerCore/SystematicTesting/TestingEngine.cs

The Json serializer removes keys with null values in the parent attributes only. If the one of the attributes has children and if the child has a key with null value, that child key is not removed. This resulted in the trace json having null values and the visualizer failed to show the trace.
The current fix recursively traverses through the event payload and removes the keys that have null values

Add logic to remove null key-value pairs in trace json

---

Src/PCompiler/CompilerCore/Compiler.cs
Src/PCompiler/CompilerCore/CompilerConfiguration.cs
Src/PCompiler/CompilerCore/ICompilerConfiguration.cs
Src/PCompiler/PCommandLine/Options/PCompilerOptions.cs
Src/PCompiler/PCommandLine/Parser/ParsePProjectFile.cs
Tst/UnitTests/Core/TestCaseFactory.cs
Tst/UnitTests/Runners/CompileOnlyRunner.cs
Tst/UnitTests/Runners/PCheckerRunner.cs
Tst/UnitTests/Runners/PrtRunner.cs

- Support compiling for multiple backend targets together. Simply add all your desired backend targets in the `<Target>` field in *.pproj file. E.g., `<Target>CSharp, PObserve, Stately, Symbolic</Target>`
- Support configuring PObserve package name through *.pproj using field `<pobserve-package>`

[CLI] Support compiling for multiple targets together

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/FFIStubGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs

Corrects spec machine name conflicts when calling spec local foreign functions
Renamed to <spec machine>Foreign to implement foreign functions local to a spec machine

[PObserve] Correct name conflict in FFI interface

---

Src/PChecker/CheckerCore/SystematicTesting/TestingEngine.cs
Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/CompilerConfiguration.cs
Src/PCompiler/CompilerCore/ICompilerConfiguration.cs
Src/PCompiler/PCommandLine/Options/PCompilerOptions.cs

This PR includes the following changes:
1. Converts P spec print statement to java logger statements instead of System.out when run in pobserve mode
2. Provides an option to enable or disable these log statements through command line option (--debug)
Usage: p compile --mode pobserve --debug (true|false)

Add option to enable/disable debug logs in pobserve mode

---

Docs/docs/manual/expressions.md

Found a typo in https://p-org.github.io/P/manual/expressions/#sizeof.
```
while (i < sizeof(sq)>) {
```
This PR fixes it.

Remove invalid '>' from while condition `(i < sizeof(sq)>)` in `P Expressions` doc

---

Tst/RegressionTests/Integration/Correct/PingPongNonDet/PingPongNonDet.p
Tutorial/2_TwoPhaseCommit/PForeign/GlobalFunctions.java
Tutorial/Common/Timer/PSrc/Timer.p

[Tutorial]
- Corrects infinite looping in Timer by allowing delayed timeout at most once. Fixes #642 
- 2PC: adds Java-equivalent of foreign function for PSym
[Tst]
- Adds a new regression test with non-deterministic jump in ping-pong example
[Testing]
- Confirmed fix for #642 by running PCover on 2PC example
````
p compile -md coverage
p check -md coverage --fail-on-maxsteps -s 10000 -tc tcSingleClientNoFailure
````
Before the fix, a cycle is detected. After the fix, no cycle is detected.

[Tutorial] Fix #642, updates 2PC, adds a new regression test

---

Src/PChecker/CheckerCore/Scheduling/TestingProcessScheduler.cs
Src/PChecker/CheckerCore/SystematicTesting/TestingEngine.cs
Src/PChecker/CheckerCore/Utilities/Profiler.cs
Src/PCompiler/PCommandLine/Options/PCheckerOptions.cs

[C# checker]
- Adds tracking memory usage.
- Adds enforcing memory limit using the `--memout` CLI option.
[CLI]
- Unhides option `-m`/`--memout` to specify memory limit in GB (default is 0 i.e., no limit)

[Bug finding] Track memory usage and enforce memory limit

---

Src/PChecker/CheckerCore/Scheduling/TestingProcessScheduler.cs
Src/PChecker/CheckerCore/SystematicTesting/TestReport.cs
Tutorial/2_TwoPhaseCommit/PForeign/ForeignCode.cs

1. Creating _pchecker_summary.txt file during PCheck

Creating _pchecker_summary.txt file during PCheck

---

Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/commandline/PExplicitConfig.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/commandline/PExplicitOptions.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/ForeignFunctionInterface.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/logger/PExplicitLogger.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/machine/PMachineId.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/machine/buffer/MessageQueue.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/Schedule.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/SchedulerInterface.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/choice/Choice.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/choice/DataChoice.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/choice/DataSearchUnit.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/choice/ScheduleChoice.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/choice/ScheduleSearchUnit.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/explicit/ExplicitSearchScheduler.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/explicit/StatefulBacktrackingMode.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/explicit/strategy/SearchStrategy.java
Src/PRuntimes/PExplicitRuntime/src/main/java/pexplicit/runtime/scheduler/explicit/strategy/SearchTask.java
Src/PRuntimes/PExplicitRuntime/src/test/java/pexplicit/TestPExplicit.java

[PEx RT]
- Serialize/deserialize memory-heavy fields of `SearchTask` as needed since taking too much space for long runs
- Added hydrid stateful backtracking that performs stateful backtracking for search within a search task only
- Adds CLI option `--stateful-backtrack <none|intra-task|all>` (default is `intra-task`). Deprecates option `--no-backtrack`
- Minor refactoring

[PEx] Adds hybrid stateful backtracking, improves storing search tasks

---

Src/PChecker/CheckerCore/PRuntime/Values/PrtSet.cs
Src/PCompiler/CompilerCore/TypeChecker/Scope.cs
Src/PRuntimes/PSymRuntime/src/test/java/psym/TestSymbolicRegression.java
Tst/RegressionTests/Integration/Correct/TestMapSet/TestMapSet.p

Fixing `key not found` error thrown when user does this:
```
var foomap: map[set[int], int];
foomap[default(set[int])] = 0;
print format("{0}", foomap[default(set[int])]);
```

Fixing "key not found" error when using set as key

---

Src/PCompiler/CompilerCore/Backend/PEx/Constants.cs
Src/PCompiler/CompilerCore/Backend/PEx/PExCodeGenerator.cs
Src/PRuntimes/PExRuntime/pom.xml
Src/PRuntimes/PExRuntime/src/main/java/pex/PEx.java
Src/PRuntimes/PExRuntime/src/main/java/pex/RuntimeExecutor.java
Src/PRuntimes/PExRuntime/src/main/java/pex/commandline/PExConfig.java
Src/PRuntimes/PExRuntime/src/main/java/pex/commandline/PExOptions.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/PExGlobal.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/logger/PExLogger.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/logger/SchedulerLogger.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/machine/MachineLocalState.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/machine/PMachine.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/scheduler/Scheduler.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/scheduler/SchedulerInterface.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/scheduler/explicit/ExplicitSearchScheduler.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/scheduler/explicit/StepState.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/scheduler/explicit/choiceselector/ChoiceQL.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/scheduler/explicit/strategy/SearchStrategy.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/scheduler/explicit/strategy/SearchStrategyAStar.java
Src/PRuntimes/PExRuntime/src/main/java/pex/runtime/scheduler/explicit/strategy/SearchTask.java
Src/PRuntimes/PExRuntime/src/main/java/pex/utils/exceptions/TooManyChoicesException.java
Src/PRuntimes/PExRuntime/src/main/java/pex/utils/monitor/MemoryMonitor.java
Src/PRuntimes/PExRuntime/src/main/java/pex/values/PMap.java
Src/PRuntimes/PExRuntime/src/test/java/pex/TestCaseExecutor.java
Src/PRuntimes/PExRuntime/src/test/java/pex/TestPEx.java
Tst/RegressionTests/Feature3Exprs/Correct/ModExpr1/modexpr1.p
Tst/RegressionTests/Feature3Exprs/DynamicError/ModExpr1/modexpr1.p
Tutorial/1_ClientServer/PSrc/Client.p
Tutorial/1_ClientServer/PTst/TestDriver.p
Tutorial/2_TwoPhaseCommit/PForeign/PExForeignCode.java

This PR adds a new bug type to PEx, called `TooManyChoicesException`, which differs it from C# backend. This exception is triggered if any of the following happens:
1. a statement with choose(.) expression gets triggered and the number of choices exceeds `--max-choices-per-call` hidden CLI option (default: 10).
2. a statement with choose(.) expression gets triggered multiple times in a single schedule and the total number of choices across these calls exceeeds `--max-choices-per-schedule` hidden CLI option (default: 100).
PEx result in these cases is a replayable buggy schedule with result `found bug of length N (too many choices)` and an exception raised with appropriate message and source code location to rectify the issue.
The rationale for this exception is to dynamically pinpoint the …

[PEx] Adds limiting data choices and sharing feedback to user

---

Src/PCompiler/CompilerCore/Backend/Uclid5/Uclid5CodeGenerator.cs
Src/PCompiler/CompilerCore/Compiler.cs
Src/PCompiler/CompilerCore/CompilerConfiguration.cs
Src/PCompiler/CompilerCore/ICompilerConfiguration.cs
Src/PCompiler/CompilerCore/Parser/PLexer.g4
Src/PCompiler/CompilerCore/Parser/PParser.g4
Src/PCompiler/CompilerCore/TypeChecker/AST/Declarations/InvariantGroup.cs
Src/PCompiler/CompilerCore/TypeChecker/AST/Declarations/ProofCommand.cs
Src/PCompiler/CompilerCore/TypeChecker/AST/Expressions/InvariantRefExpr.cs
Src/PCompiler/CompilerCore/TypeChecker/DeclarationStubVisitor.cs
Src/PCompiler/CompilerCore/TypeChecker/DeclarationVisitor.cs
Src/PCompiler/CompilerCore/TypeChecker/ExprVisitor.cs
Src/PCompiler/CompilerCore/TypeChecker/Scope.cs
Src/PCompiler/PCommandLine/Options/PCompilerOptions.cs
Tutorial/6_TwoPhaseCommitVerification/Single_Incremental/PSrc/System.p
Tutorial/6_TwoPhaseCommitVerification/Single_Incremental/TwoPhaseCommitVerification.pproj

New features:
- `prove X using Y`, which is equivalent to `requires X, Y; ensures X`; You can write `prove X using *` which will put all invariants other than X to the `requires`. Similarly, you can write `prove *;` which is equivalent to proving all invariants in one shot.
- Parallelization: `verify()` calls in Uclid5 are parallelized now; by default, it uses half the host machine's cores. You can specify the number of cores to use by passing `-j <num cores>` in the command line argument.
- `Lemma` and `Theorem` block for bundling invariant declarations, which can be referred to in the `prove X using Y` commands
Please see the example [here](https://github.com/AD1024/P/blob/83cdec91339330bd927485f9444712046223edb7/Tutorial/6_TwoPhaseCommitVerification/Single_Incremental/PSrc/System.p#L88- …

[Feature] `prove * using *` command for incremental proof construction

---

Src/PChecker/CheckerCore/Runtime/Events/EventInfo.cs
Src/PChecker/CheckerCore/Runtime/StateMachines/EventQueues/EventQueue.cs
Src/PChecker/CheckerCore/Runtime/StateMachines/StateMachine.cs
Src/PChecker/CheckerCore/Runtime/VectorTime.cs
Src/PChecker/CheckerCore/SystematicTesting/ControlledRuntime.cs
Src/PChecker/CheckerCore/SystematicTesting/Strategies/Feedback/Coverage/BehavioralObserver.cs
Src/PChecker/CheckerCore/SystematicTesting/TestingEngine.cs

Currently the BehavioralObserver calculates the uniqueness score for each schedule's timeline and prints the score out in the console. Next step is to integrate/replace the TimelineObserver with BehavioralObserver. 
The uniqueness score is calculated through MinHash. The function randomly chooses 100 elements (each element is a tuple of (vector time, event, SEND/DEQUEUE enum)) from the current timeline and compare them with all past timelines. The final score is the average number of miss-matches between the current timeline and the past timelines. If there is a duplicate timeline int the past, the uniqueness score will be 0.

Added VectorTime and BehavioralObserver class for feedback strategy

---

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs
Src/PCompiler/CompilerCore/Backend/Java/JavaSourceGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Src/PCompiler/CompilerCore/Backend/Java/TypeManager.cs

- Reverted PEvent Java code generation bug introduced in P Checker clean up
- Added the JEvent case to the existing handling of immutable types (like JString and JEnum)
- Changed the default value for JEvent to be null

Java code generation fixes

---

Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs

Previously, normal if/else statements would be formatted like:
if..
{
}
else
{
}
and if/else blocks with an empty if block would be formatted like: if...
{} else
{
}
Made all if/else statments be formatted like
if
{
}
else
{
}

Fix odd indenting of "else" in generated Java code

---

Src/PChecker/CheckerCore/SystematicTesting/TestingEngine.cs
Src/PCompiler/PCommandLine/Options/PCheckerOptions.cs
Tst/CorrectLogs/bugs2/Main.coverage.txt
Tst/CorrectLogs/bugs2/trace_0_0.trace.json
Tst/CorrectLogs/bugs2/trace_0_0.txt
Tst/UnitTests/PCheckerLogGeneratorTests.cs
Tst/UnitTests/Runners/PCheckerRunner.cs
Tst/UnitTests/TestAssertions.cs
Tst/UnitTests/UnitTests.csproj

Added test for PChecker log generation against p model: Feature1SMLevelDecls/DynamicError/bug2/bug2.p. 
Also removed "timeline.txt" generation since nothing gets written into this file currently.

Added test for generated PChecker logs

---

.github/workflows/macosci.yml
.github/workflows/ubuntuci.yml
Src/PCompiler/PCommandLine/Options/PCheckerOptions.cs

Fixed the error `Error: Could not find any *.dll file.` by changing the PChecker search directory name from `CSharp` to `PChecker` to match the generated `PGenerated/PChecker` directory name.

Fix PChecker .dll file not found

---

Src/PChecker/CheckerCore/SystematicTesting/TestReport.cs
Src/PChecker/CheckerCore/SystematicTesting/TestingEngine.cs
Tst/CorrectLogs/bugs2/Main_0_0.txt

- Removed console output that contains feedback strategy stats
- Before:
``` 
... Checker is using 'feedbackpct' strategy (seed:3297452164).
..... Schedule #1
..... Total saved: 1, pending mutations: 0, visited generators: 0
..... Schedule #2
..... Total saved: 2, pending mutations: 49, visited generators: 1
..... Schedule #3
..... Total saved: 3, pending mutations: 48, visited generators: 1 
```
- After:
```
... Checker is using 'feedbackpct' strategy (seed:3938377194).
..... Schedule #1
..... Schedule #2
..... Schedule #3
```
- Uncommented timeline console output since the feedbackpct issue is fixed

Remove feedback strategy stats dump in console

---

Src/PCompiler/CompilerCore/DefaultCompilerOutput.cs
Src/PCompiler/PCommandLine/CommandLineOutput.cs

Use console default color instead of white for p cli info messages. This will make the info messages easier to read, regardless of the user's theme.

Use foreground color in p cli text for theme compatibility

---

Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs

Generate a toString() method in the Java code when compiling in pobserve mode; it uses the same format as for types

Add toString() to generated Java code for spec machines in pobserve mode

---

Src/PCompiler/CompilerCore/Backend/PEx/PExCodeGenerator.cs
Src/PCompiler/CompilerCore/Backend/PEx/TransformASTPass.cs
Src/PCompiler/CompilerCore/Compiler.cs
Src/PRuntimes/PExRuntime/src/test/java/pex/TestPEx.java

[PEx IR]
- Throw compile-time exception for receive statement inside loop with appropriate message
[PEx RT]
- Exclude tests with receive inside loop
[PCompiler]
- Adds try/catch to gracefully report not-supported errors during compiling for PEx

[PEx] Disable support for receive statement inside loop

---

Src/PCompiler/CompilerCore/Compiler.cs
Tst/RegressionTests/Feature1SMLevelDecls/StaticError/LexerError1/LexerError1.p
Tst/RegressionTests/Feature1SMLevelDecls/StaticError/LexerError2/LexerError2.p

Previously, the p compiler was silently skipping over unexpected characters encountered during lexical analysis.  Added a listener on the lexer to raise an error when lexical analysis encounters an error.
Added unit tests to verify this behavior.

Change p compiler to return a syntax error for lexical errors

---

.github/workflows/macosci.yml
.github/workflows/ubuntuci.yml
Src/PCompiler/CompilerCore/Backend/PVerifier/Uclid5CodeGenerator.cs
Src/PCompiler/CompilerCore/CompilerConfiguration.cs
Src/PCompiler/CompilerCore/ICompilerConfiguration.cs
Src/PCompiler/CompilerCore/Parser/PParser.g4
Src/PCompiler/CompilerCore/TypeChecker/AST/Declarations/ProofBlock.cs
Src/PCompiler/CompilerCore/TypeChecker/AST/Declarations/ProofCommand.cs
Src/PCompiler/CompilerCore/TypeChecker/DeclarationStubVisitor.cs
Src/PCompiler/CompilerCore/TypeChecker/DeclarationVisitor.cs
Src/PCompiler/CompilerCore/TypeChecker/Scope.cs
Src/PCompiler/PCommandLine/Options/PCompilerOptions.cs
Tutorial/Advanced/2_TwoPhaseCommitVerification/Single/PSrc/System.p

This PR adds the support of *named proof blocks*.
For instance (snippet from 2PC proof from Tutorial):
```
Proof system_configs {
prove system_config;
prove default using system_config;
}
Proof kondo_proof {
prove kondo using system_config;
prove safety using kondo, system_config_participant_set;
}
```
Now, we can run PVerifier with `p compile -pb system_configs`, which will only emit UCLID queries for proof commands in `system_configs`.

[feature] Checking individual proof blocks via `-pb`

---

Src/PCompiler/CompilerCore/Backend/PVerifier/Uclid5CodeGenerator.cs
Src/PCompiler/CompilerCore/TypeChecker/AST/Declarations/Invariant.cs

1. Add sanity checks (received is a subset of sent) as preconditions to each procedure.
2. Extend `default` with sanity checks.
3. Fix the missing remaining invariants (`LEMMA`) when `prove default using LEMMA`
4. Update received buffer after inlined procedure.

[FIX] Add sanity check to default

---

Docs/docs/advanced/PVerifierLanguageExtensions/install-pverifier.md

This  pull request corrects some typos in the PVerifier installation instructions on Amazon Linux, and adds instructions like installing .NET 8.0 and installing maven, python 3, and gcc 10 and g++ 10 that are missing when installing on top of a fresh installation of Amazon Linux 2.  
I also removed the comment "follow regular P install instructions" for the P installation instructions, because I misinterpreted this explanation as an instruction to go follow the regular P [build instructions](https://github.com/p-org/P/blob/master/Docs/docs/getstarted/build.md).
I'm not sure what the `!!! success` and `??? hint` tags are, but the don't seem to be formatting as intended (eg, `java -version` is formatted as `shell java version`).

Expand installation instructions for PVerifier on Amazon Linux 2

---

Src/PCompiler/CompilerCore/TypeChecker/Analyzer.cs
Src/PCompiler/CompilerCore/TypeChecker/DeclarationVisitor.cs
Src/PCompiler/CompilerCore/TypeChecker/ProofBlockVisitor.cs

This PR fixes the issue where the compiler raises type checking errors when the projection of a machine/event is used before their declarations are populated.
@FedericoAureliano Please take a look and let me know if there are other types of declarations need similar changes. Thanks!

[fix] Postpone type checking of invariants, axioms, init-conditions and pure functions

---

.github/workflows/maven-publish.yml
Src/PCompiler/CompilerCore/Backend/PEx/Constants.cs
Src/PEx/pom.xml

- Tested by manually triggering Github maven publish action to publish PEx v0.4.1 and verified the PEx maven version on maven central page: https://central.sonatype.com/artifact/io.github.p-org/pex
- Haven't tested the automated publish to maven when P is publishing because we will need to publish a new version of P to test it.

Updating PEx Maven Publishing Github action

---

Tutorial/Common/Timer/PSrc/Timer.p

Addresses the issue in #876. Namely, a timer can introduce liveness bugs because the current timer can just not fire and thus algorithms relying on a timer to kick in might never finish. Also the timer kicks in too quickly which can lead to livelock problems. This PR fixes the issues as follows: we reduce the chance of the timer kicking in to 1/10 which leads to fewer livelock problems and we make sure the timer cannot end in a state where it cannot kick in.

Prevent liveness issues due to timers

---

Src/PCompiler/CompilerCore/Compiler.cs
Tutorial/5_Paxos/PSpec/common.p
Tutorial/6_Raft/Raft.pproj

Also fixes the Paxos model to avoid using `targets` as a parameter name

[PVerifier] exception handling for PVerifier-specific tokens

---

Docs/docs/advanced/PVerifierLanguageExtensions/announcement.md
Docs/docs/advanced/PVerifierLanguageExtensions/outline.md
Docs/docs/advanced/PVerifierLanguageExtensions/using-pverifier.md
Docs/mkdocs.yml

Noticed that the PVerifier pages were not showing up on the P wiki.
This PR fixes the issue by ensuring the pages are included correctly.
Changes
- Updated wiki configuration/links.
- Verified that PVerifier pages now render properly.

Fix PVerifier pages not showing up correctly on P wiki
