p-org/P

Bld/Targets/compiler.targets, Bld/build.sh, Src/CMakeLists.txt, Src/Pc/Compiler/Compiler.csproj, Src/Prt/CMakeLists.txt, Src/Prt/LinuxUser/PrtLinuxUserConfig.c, Src/Prt/LinuxUser/PrtLinuxUserConfig.h, Src/Prt/LinuxUser/ext_compat.h, Src/Prt/LinuxUser/sal.h
=> Revert "Revert "build P using mono and CMake(for Prt)""

Src/Pc/Compiler/Compiler.csproj
=> Platform dependent dll for formulatask

Src/PSharpRuntime/PSharpExtensions/PEvent.cs, Src/PSharpRuntime/PSharpExtensions/PLogger.cs, Src/PSharpRuntime/PSharpExtensions/PModule.cs, Src/PSharpRuntime/PSharpExtensions/PrtSharp.csproj, Src/Pc/CompilerCore/Backend/PSharp/PSharpCodeGenerator.cs, Src/Samples/PingPongPSharp/Main.cs, Src/Samples/PingPongPSharp/PingPongPSharp.csproj, Src/Samples/TwoPhaseCommit/Main.cs, Src/Samples/TwoPhaseCommit/PSrc/Client.p, Src/Samples/TwoPhaseCommit/PSrc/Coordinator.p, Src/Samples/TwoPhaseCommit/PSrc/Events.p, Src/Samples/TwoPhaseCommit/PSrc/Participant.p, Src/Samples/TwoPhaseCommit/PSrc/Spec.p, Src/Samples/TwoPhaseCommit/PSrc/TestDriver.p, Src/Samples/TwoPhaseCommit/PSrc/Timer.p, Src/Samples/TwoPhaseCommit/TwoPhaseCommit.csproj, Tst/UnitTests/UnitTests.csproj
=> Update p sharp version

Src/PSharpRuntime/PSharpExtensions/PEvent.cs, Src/PSharpRuntime/PSharpExtensions/PLogger.cs, Src/PSharpRuntime/PSharpExtensions/PrtSharp.csproj, Src/Pc/CompilerCore/Backend/PSharp/PSharpCodeGenerator.cs, Src/Samples/PingPongPSharp/Main.cs, Src/Samples/PingPongPSharp/PingPongPSharp.csproj, Src/Samples/PingPongPSharp/Test.cs, Src/Samples/TwoPhaseCommit/Main.cs, Src/Samples/TwoPhaseCommit/TwoPhaseCommit.csproj, Tst/UnitTests/UnitTests.csproj
Updated the PSharpVersion and started using the new Logging Interface in P#
=> Psharp1.6.9

Src/PSharpRuntime/PSharpExtensions/PMachine.cs, Src/PSharpRuntime/PSharpExtensions/PrtSharp.csproj, Src/PSharpRuntime/PSharpExtensions/Values/HashHelper.cs, Src/PSharpRuntime/PSharpExtensions/Values/PrtTuple.cs, Src/Pc/CompilerCore/Backend/PSharp/PSharpCodeGenerator.cs
=> PrtSharp bugs and extensions

.github/workflows/macosci.yml, .github/workflows/release.yml, .github/workflows/ubuntuci.yml, .github/workflows/windowsci.yml, Bld/build.sh, Src/PCompiler/CommandLine/CommandLine.csproj, Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeCompiler.cs, Src/PCompiler/CompilerCore/CompilerCore.csproj, Src/PRuntimes/CSharpRuntime/CSharpRuntime.csproj, Tst/RegressionTests/Rvm/Example/getconsistency/gen_monitor.py, Tst/RegressionTests/Rvm/Example/twophasecommit/gen_monitor.py, Tst/RegressionTests/Rvm/run_unittest.py, Tst/UnitTests/Runners/CoyoteRunner.cs, Tst/UnitTests/UnitTests.csproj, Tutorial/README.md
=> Update DotNet version from 3.1 to 5.0

.github/workflows/macosci.yml, .github/workflows/release.yml, .github/workflows/ubuntuci.yml, .github/workflows/windowsci.yml, Bld/build.sh, Src/PCompiler/CommandLine/CommandLine.csproj, Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeCompiler.cs, Src/PCompiler/CompilerCore/CompilerCore.csproj, Src/PRuntimes/CSharpRuntime/CSharpRuntime.csproj, Tst/RegressionTests/Rvm/Example/getconsistency/gen_monitor.py, Tst/RegressionTests/Rvm/Example/twophasecommit/gen_monitor.py, Tst/RegressionTests/Rvm/run_unittest.py, Tst/UnitTests/Runners/CoyoteRunner.cs, Tst/UnitTests/UnitTests.csproj, Tutorial/README.md
=> Revert "Update DotNet version from 3.1 to 5.0"

Src/PRuntimes/PCSharpRuntime/Values/PrtTuple.cs, Tst/RegressionTests/Feature3Exprs/Correct/SingleNamedTuple1/singlenamedtuple.p, Tst/RegressionTests/Feature3Exprs/Correct/SingleNamedTuple2/singlenamedtuple.p
This problem should be fixed now and there should not be any problem using tuples with single element in it.
Thanks for repros @nicolagi
=> Fixed a (long standing) silly bug in the Tuple implementation with a single element in it

Src/PCompiler/CompilerCore/Backend/Java/JavaCodeGenerator.cs
The Java code generator accumulates the argument types for all Functions in
advance.  This allows us to emit a specific event type rather than an abstract
`PEvent` type for the function argument.  However, when mapping Functions
to their PEvent arguments, `.Add()` was used rather than direct dictionary
indexing.  The former throws an exception if a key already exists.  This is
problematic in the following example:
```
1  type t = (a : seq[int]);
2
3  event ev : t;
4
5  spec foo observes ev {
6
7    fun Handler(req: t) {
8
9    }
10
11    start state Init {
12      on ev do Handler;
13    }
14
15    state Other {
16      on ev do Handler;
17    }
18
19  }
```
This is safe to do; the second assocation between `Handler` and `ev`
should be a no-op, but the current implementation would raise …
=> [Java] Correctly handle event handler reuse across multiple states

Src/PCompiler/CompilerCore/Backend/Java/JavaCodeGenerator.cs
This is an issue that I realised when working on https://github.com/p-org/P/pull/444 earlier today:
Anonymous event handlers need not consume the event, such as here:
```
1  type t = (a : seq[int]);
2  event ev : t;
3
4  event ev2 : int;
5
6  spec foo observes ev, ev2 {
7    start state Init {
8      on ev, ev2 do {
9
10      }
11    }
12
13  }
```
Even though `ev` and `ev2` have incompatable payload types, this code is still
safe since we never do anything with the payload.  However, the current code generator
would incorrectly emit a parameter to the generated method, which would cause
the generated Java code to fail typechecking, like so.
```
58         private void Anon(ev pEvent) {
59
60         }
...
64             addState(new State.Builder(INIT_STATE)
65 …
```
=> [Java] emit right fn signature for handler of no arguments

Src/PCompiler/CompilerCore/Backend/Java/JavaCodeGenerator.cs
This now generates plain old java classes for records, which were introduced in Java 14 and are not supported by the version of Java that we need.
Example output:
```
event eIncrVal : (i : int);
```
```java
public static class eIncrVal implements PObserveEvent.PEvent<PTuple_i> {
public eIncrVal(PTuple_i p) { this.payload = p; }
private PTuple_i payload;
public PTuple_i getPayload() { return payload; }
@Override
public boolean equals(Object o) {
if (this == o) return true;
if (o == null || getClass() != o.getClass()) return false;
eIncrVal that = (eIncrVal)o;
return Values.deepEquals(this.payload, that.payload);
}
@Override
public int hashCode() { return Objects.hash(payload); }
@Override
public String toString() {
return "eIncrVal[" + payload + "]";
} // toString()
} // PEvent definition …
```
=> [Java] emit POJOs rather than records for PEvents

Docs/docs/getstarted/install.md
This is not an important patch at all, but I had a few minutes to kill while waiting for a VM to provision ;)
=> [Docs] make mention of the Vim P plugin

Src/PCompiler/CompilerCore/Backend/Java/TypesGenerator.cs, Src/PRuntimes/PJavaRuntime/src/test/java/tutorialmonitors/clientserver/PTypes.java
Just a nit I just noticed; after construction, fields shouldn't be modifiable.
=> [Java] Tuples' fields should be final

Src/PRuntimes/PJavaRuntime/pom.xml
This got changed at some point and my life has been a garage sale ever since
=> [Java] PRT to use 1.0-SNAPSHOT

Src/PCompiler/CompilerCore/Backend/Java/TypesGenerator.cs
Partially addresses some issues found by @beyazit-yalcinkaya .
=> [Java] accumulate tuple definitions in inner scopes (#478)

Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs, Src/PRuntimes/PJavaRuntime/src/test/java/testmonitors/clientserver/ClientServerTest.java, Src/PRuntimes/PJavaRuntime/src/test/java/testmonitors/clientserver/PMachines.java
Previously these were written by hand, but there's no need for that.  The provider is now an inner class of the monitor, so the class name in the JAR would be something like `PMachines$GuaranteedWithDrawProgress$Supplier`.
=> [Java] generate code for monitor providers

Bld/build.sh, Tst/PUnit/.gitignore, Tst/PUnit/README.md, Tst/PUnit/log4j2.xml, Tst/PUnit/pom.xml, Tst/PUnit/src/main/java/punit/ObservableAppender.java, Tst/PUnit/src/main/java/punit/PSpecInterceptor.java, Tst/PUnit/src/main/java/punit/annotations/PAssertExpected.java, Tst/PUnit/src/main/java/punit/annotations/PSpecTest.java, Tst/PUnit/src/main/java/punit/exceptions/PAssertMismatchExeception.java, Tst/PUnit/src/test/java/RingEventParserTest.java, Tst/PUnit/src/test/java/RingTest.java, Tst/PUnit/src/test/java/sample/sampleimpl/Ring.java, Tst/PUnit/src/test/java/sample/samplespec/PEvents.java, Tst/PUnit/src/test/java/sample/samplespec/PTypes.java, Tst/PUnit/src/test/java/sample/samplespec/RingEventParser.java, Tst/PUnit/src/test/java/sample/samplespec/RingSpec.java
Not sure if there's a great place for this to live, but maybe it may as well be here?
Note that this is the version with the interface in the poster, not precisely the one being used for Jigar's tests, as that one requires some implementation details from the project being built internally that is not public :-) .
=> [PUnit] initial commit

.github/workflows/psym.yml
Creates a CI for building and testing PSym. Merging in tests-fix which contains various fixes for PSym.
=> [PSym] Create HitHub action for build and test

Src/PCompiler/CompilerCore/Backend/CSharp/CSharpNameManager.cs, Tst/RegressionTests/Feature3Exprs/Correct/issue511/issue511.p
Sanitize identifiers in C# code generator
=> [PCompiler] Fix #511

Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeGenerator.cs, Src/PCompiler/CompilerCore/DefaultTranslationErrorHandler.cs, Src/PCompiler/CompilerCore/ITranslationErrorHandler.cs, Src/PCompiler/CompilerCore/TypeChecker/AST/Declarations/Function.cs, Src/PCompiler/CompilerCore/TypeChecker/Analyzer.cs, Src/PCompiler/CompilerCore/TypeChecker/ExprVisitor.cs, Src/PCompiler/CompilerCore/TypeChecker/StatementVisitor.cs, Src/PRuntimes/PCSharpRuntime/PMachine.cs, Src/PRuntimes/PCSharpRuntime/PMonitor.cs, Tst/RegressionTests/Feature1SMLevelDecls/DynamicError/StaticFunctionInMonitor/StaticFunctionInMonitor.p, Tst/RegressionTests/Feature1SMLevelDecls/StaticError/SendInMonitor/SendInMonitor.p, Tst/RegressionTests/Feature1SMLevelDecls/StaticError/SideEffectsInMonitor/SideEffectsInMonitor.p, Tst/RegressionTests/Feature1SMLevelDecls/StaticError/StaticFunctionInMonitor/StaticFunctionInMonitor.p
This also fixes the issue #303
=> Fix the code generation error for static functions called from Monitors

.github/workflows/maven-publish.yml, Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/EntryPoint.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/machine/Machine.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/IterativeBoundedScheduler.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/Scheduler.java
Adds minor changes and updates to PSym
=> [PSym] Minor updates

Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeGenerator.cs, Src/PCompiler/CompilerCore/Backend/CSharp/Constants.cs, Src/PCompiler/PCommandLine/CommandLine.cs, Src/PCompiler/PCommandLine/PCommandLine.csproj, Src/PRuntimes/PSymRuntime/pom.xml, Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/util/ValueSummaryUnionFind.java
- Programmatically set the dependency version in the generated `<project-name>.csproj`
- Minor corrections to PSym (relating to union-find with dynamic machine creation)
=> [2.0] Updates

.github/workflows/psym.yml, Src/PCompiler/CompilerCore/Backend/Symbolic/SymbolicCodeGenerator.cs, Src/PRuntimes/PSymRuntime/pom.xml, Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/PSymConfiguration.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/PSymOptions.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/IterativeBoundedScheduler.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/Scheduler.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/MapVS.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/StringVS.java
- [PSym] Update metrics printed to console based on exploration strategy
- [PSym] Update how depth counting is done in the presence of sync events
- [PSym, PCompiler] Improve support for string value summary with `format(.)`
=> [PSym] Updates

Src/PCompiler/CompilerCore/TypeChecker/ModuleExprVisitor.cs
=> Removed the unwanted requirement around Main function needed when no test case is declared

Src/PChecker/CheckerCore/Actors/Logging/ActorRuntimeLogTextFormatter.cs, Src/PChecker/CheckerCore/Actors/Logging/ActorRuntimeLogXmlFormatter.cs, Src/PChecker/CheckerCore/Actors/Logging/IActorRuntimeLog.cs, Src/PChecker/CheckerCore/Actors/Logging/LogWriter.cs, Src/PChecker/CheckerCore/Coverage/ActorRuntimeLogEventCoverage.cs, Src/PChecker/CheckerCore/Coverage/ActorRuntimeLogGraphBuilder.cs, Src/PChecker/CheckerCore/Specifications/Monitors/Monitor.cs, Src/PCompiler/CompilerCore/Backend/CSharp/CSharpNameManager.cs, Src/PRuntimes/PCSharpRuntime/GodMachine.cs, Src/PRuntimes/PCSharpRuntime/PLogFormatter.cs, Src/PRuntimes/PCSharpRuntime/PMachine.cs
Added information for Announce statements and also monitor process events.
=> Fixed the trace log

Docs/docs/getstarted/build.md, README.md
This just adds some basic instructions for removing an existing P installation and testing changes locally before opening a pull request.
=> Add some docs about building and testing locally

.github/workflows/pcover.yml, README.md, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/PSymGlobal.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/logger/ScheduleWriter.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/machine/buffer/SymbolicQueue.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/Scheduler.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/explicit/ExplicitSearchScheduler.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/replay/ReplayScheduler.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/utils/Assert.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/valuesummary/SetVS.java, Src/PRuntimes/PSymRuntime/src/test/java/psym/TestSymbolicRegression.java
[PCover]
- Add GitHub action for explicit-state checker
- Improve error reported due to detected cycles in a schedule
- Cleanup when liveness checks are enforced
[PSym]
- Improve fix point detection (enabled via `--state-caching exact` CLI option)
- Minor correction to corner-case symbolic set comparison
=> [PCover] Add CI

Src/Scripts/TutorialsChecker/check.sh
Increase number of iterations for Tutorials CI
=> [CI] Update Tutorials CI

Src/PRuntimes/PCSharpRuntime/PEvent.cs, Tst/RegressionTests/Feature3Exprs/Correct/events1/events1.p
Event comparison when added to collections was buggy. This PR fixes the issue.
=> Fixed a bug in events comparison.

Docs/docs/getstarted/PeasyIDE.md, Docs/docs/getstarted/install.md, Docs/mkdocs.yml, Src/PCompiler/CompilerCore/Backend/Stately/StatelyCodeGenerator.cs
1. Update "IDE for P" section in the P documentation
2. Fix stately code generator bug that throws key not found error
=> Update docs and fix stately generator code bug

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs, Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Adding Serializable interface implementation for the purpose of serializing properly with flink.
=> add serializable to the Supplier in generated Java code.

.github/workflows/psymb.yml, Src/PCompiler/CompilerCore/Backend/Symbolic/Constants.cs, Src/PRuntimes/PSymRuntime/pom.xml, Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/PSymConfiguration.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/PSymOptions.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/Scheduler.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/SearchScheduler.java
[PSym]
- Support liveness checking with bounded symbolic mode
- Initial support for bounded symbolic iterative with dynamic machine creation
- Minor renaming
=> [PSym] Support liveness checking with bounded symbolic

Docs/docs/manual/statemachines.md
Updates the P state machines page. Resolves #677 
@ankushdesai Careful review needed. Feel free to make changes and push any update/rewriting you see fit.
=> [Docs] Updates P State Machines page

Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeGenerator.cs, Src/PCompiler/CompilerCore/Backend/IRTransformer.cs, Src/PRuntimes/PSymRuntime/src/test/java/psym/TestSymbolicRegression.java, Tst/RegressionTests/Feature2Stmts/Correct/foreach2/foreach2.p, Tst/RegressionTests/Feature2Stmts/Correct/foreach3/foreach3.p, Tst/RegressionTests/Feature2Stmts/Correct/foreach4/foreach4.p, Tst/RegressionTests/Feature2Stmts/DynamicError/foreach2/foreach2.p, Tst/RegressionTests/Feature2Stmts/DynamicError/foreach3/foreach3.p, Tst/RegressionTests/Feature2Stmts/DynamicError/foreach4/foreach4.p
[PCompiler]
Corrects foreach to while transformation to account for possible continue statement in loop body
[Tst]
Adds regression test for foreach with continue
=> [PCompiler] Correct foreach -> while transformation 

Src/PCompiler/CompilerCore/Backend/IRTransformer.cs, Tst/RegressionTests/Feature3Exprs/Correct/assertMessage/assertMessage.p
Fixes the issue reported in #671.
=> Fixes the early evaluation problem with assert statements in P

Src/PCompiler/CompilerCore/Backend/Symbolic/TransformASTPass.cs, Src/PRuntimes/PSymRuntime/pom.xml, Src/PRuntimes/PSymRuntime/src/main/java/psym/commandline/PSymOptions.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/logger/TraceLogger.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/replay/ReplayScheduler.java, Src/PRuntimes/PSymRuntime/src/main/java/psym/runtime/scheduler/search/explicit/ExplicitSearchScheduler.java
[PCompiler]
- Corrects symbolic codegen backend to not duplicate common statements in if statement with receives
[PCover]
- Update verbose mode printing to include sender machine in explicit-state search and in CEX replayer
=> [PSym/PCover] Minor updates

Bld/build.sh, Docs/docs/getstarted/install.md, Docs/docs/old/getstarted/install.md, Src/PRuntimes/PSymRuntime/scripts/run_pchecker.sh, Src/PRuntimes/PSymRuntime/scripts/run_psym.sh, Tutorial/1_ClientServer/portfolio-config.json
- Updated paths in build scripts
- Updated documentation with .net 8.0 installation
=> Update build scripts and docs

Src/PChecker/CheckerCore/SystematicTesting/TestingEngine.cs
Wrote a custom converter to handle serialization changes from .NET6 to .NET8.
=> Create custom converter for JSON serialization in .NET8

Src/PChecker/CheckerCore/Scheduling/TestingProcessScheduler.cs, Src/PChecker/CheckerCore/SystematicTesting/TestReport.cs
Adding "max_memory" to pchecker_summary.txt
=> Adding "max_memory" to pchecker_summary.txt

Tutorial/PriorityQueue/PForeign/ClientFunctions.cs, Tutorial/PriorityQueue/PForeign/PriorityQueue.cs, Tutorial/PriorityQueue/PForeign/PriorityQueueFunctions.cs
Updating import from Plang to PChecker in PriorityQueue tutorial
=> Updating import from Plang to PChecker

Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs, Src/PRuntimes/PJavaRuntime/src/main/java/prt/Monitor.java, Src/PRuntimes/PJavaRuntime/src/test/java/MonitorTest.java, Src/PRuntimes/PJavaRuntime/src/test/java/testcases/clientserver/PMachines.java, Src/PRuntimes/PJavaRuntime/src/test/java/testcases/espressomachine/EspressoMachine.java, Src/PRuntimes/PJavaRuntime/src/test/java/testcases/failuredetector/FailureDetector.java, Src/PRuntimes/PJavaRuntime/src/test/java/testcases/twophasecommit/TwoPhaseCommit.java
1. Remove optional parameters in Monitor to make monitor serializable
2. Make monitor object reinitializable from deserialized object
3. Changes made to Java machine code generator to generate necessary changes
=> Remove optional parameters in Monitor

Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeGenerator.cs, Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs, Src/PCompiler/CompilerCore/Backend/Symbolic/SymbolicCodeGenerator.cs, Src/PCompiler/CompilerCore/Backend/Symbolic/TransformASTPass.cs, Src/PCompiler/CompilerCore/TypeChecker/AST/Declarations/Function.cs, Src/PCompiler/CompilerCore/TypeChecker/Analyzer.cs, Src/PCompiler/CompilerCore/TypeChecker/StatementVisitor.cs
Clean up some unnecessary use of `bool?`, floated around several places.
=> [clean-up] unnecessary option types

Tst/RegressionTests/Feature1SMLevelDecls/Correct/EntryNamedFunction1/EntryNamedFunction1.p, Tst/RegressionTests/Feature1SMLevelDecls/DynamicError/EntryNamedFunction/EntryNamedFunction.p, Tst/RegressionTests/Feature1SMLevelDecls/StaticError/EntryNamedFunction1/EntryNamedFunction1.p, Tst/RegressionTests/Feature1SMLevelDecls/StaticError/EntryNamedFunction2/EntryNamedFunction2.p, Tst/RegressionTests/Feature1SMLevelDecls/StaticError/EntryNamedFunction3/EntryNamedFunction3.p
Added 1- correct tests, 1-dynamic tests, 3-static tests for Entry Named Functions
=> Added Unit tests for Entry Named Functions

.github/workflows/publishdocs.yml
=> revert publishdocs.yml changes

Src/PChecker/CheckerCore/Runtime/Logging/PCheckerLogJsonFormatter.cs, Src/PChecker/CheckerCore/SystematicTesting/ControlledRuntime.cs, Src/PChecker/CheckerCore/Testing/TestingProcess.cs, Src/PCompiler/CompilerCore/Backend/CSharp/CSharpCodeGenerator.cs
This PR fixes the Json log generating issue. Will create a new PR for logger test.
Tested generated json file with PEasy visualizer, made sure no duplicate log entries for print and announce statements.
=> Fixed json log generation bug

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs, Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Update java code generator to generate "com.amazon.pobserve.runtime" imports in place of "prt" imports
=> Update java generator code to output updated prt imports

Src/PChecker/CheckerCore/SystematicTesting/Strategies/Feedback/PCTScheduler.cs
Fix feedback strategy pct error
=> Fix feedback strategy pct

Src/PCompiler/CompilerCore/DefaultTranslationErrorHandler.cs, Src/PCompiler/CompilerCore/ITranslationErrorHandler.cs, Src/PCompiler/CompilerCore/TypeChecker/AST/Declarations/Variable.cs, Src/PCompiler/CompilerCore/TypeChecker/ModuleExprVisitor.cs, Src/PCompiler/CompilerCore/TypeChecker/ParamAssignment.cs, Tst/TestParamTester/1_ClientServer/PTst/Testscript.p, Tst/UnitTests/TypeChecker/ParamAssignmentTest.cs
+ new allow twise number be 1
+ unify twise number valid condition
+ add unit test
=> T-wise combinatorial (Solved Concerns from Lewis)

Src/PCompiler/CompilerCore/Backend/PVerifier/Uclid5CodeGenerator.cs
This PR fixes:
- Checksum compute: ignore the line that passes solver options
- Caching should be skipped for proofs that time out.
=> [fix] proof caching: checksum & skip caching for proofs that timeout

Src/PCompiler/CompilerCore/Backend/PVerifier/Uclid5CodeGenerator.cs
These errors were ignored in error reporting (which should not be)
=> [tweak] error reporting for loop invariants

Src/PCompiler/CompilerCore/Backend/Java/Constants.cs, Src/PCompiler/CompilerCore/Backend/Java/MachineGenerator.cs
Modify the Java code generator so that it imports pobserve dependency classes from the Maven central published packages
=> Update java generator code to generate updated imports from maven

Src/PChecker/CheckerCore/Testing/TestingProcess.cs
Fixes the issue where test cases being printed twice
=> Fix list tests lists duplicated tests
